/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs.grifisaa.patterns.facade;

public class App {

    public static void main(String[] args) {
        // instantiate components here

        HomeTheaterFacade homeTheater = new HomeTheaterFacade(amp, tuner, dvd, cd, projetor, screen, lights, popper);

        homeTheater.watchMovie("Raiders of the lost Ark");
        homeTheater.endMovie();
    }
}
