/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs3321.javalin;

import io.javalin.Javalin;

import java.net.http.HttpClient;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;

public class App {
    public static void main(String[] args) {
        Javalin app = Javalin.create().start(7000);
        app.get("/", ctx -> ctx.html("<body><h1>Hello World!</h1></ody>"));
        app.get("/api/status", new StatusHandler());
        app.get("/api/user", ctx -> ctx.json(new User("Isaac", "Griffith", "grifisaa@isu.edu")));
        app.post("/api/user/", ctx -> System.out.println(ctx.bodyAsClass(User.class)));

        HttpClient client = HttpClient.newBuilder()
                .version(HttpClient.Version.HTTP_1_1)
                .followRedirects(HttpClient.Redirect.NORMAL)
                .connectTimeout(Duration.ofSeconds(20))
                .build();


    }
}
