/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs.cs3321.sql;

import edu.isu.cs.cs3321.sql.model.Customer;
import edu.isu.cs.cs3321.sql.model.Order;
import edu.isu.cs.cs3321.sql.model.Product;
import org.javalite.activejdbc.DB;

public class App {

    /**
     * @param args
     */
    public static void main(String[] args) {
        new DB("default").open("com.mysql.cj.jdbc.Driver",
                "jdbc:mysql://localhost/test_db?serverTimezone=America/Denver",
                "user",
                "password");

        Customer bob = Customer.findFirst("name = ?", "Bob Sampson");
        Customer julie = Customer.findFirst("name = ?", "Julie Lark");

        if (bob == null) {
            bob = new Customer();
            bob.set("name", "Bob Sampson");
            bob.set("address", "123 Some St.");
            bob.set("city", "Pocatello");
            bob.set("state", "ID");
            bob.set("postal_code", "83201");
            bob.saveIt();

            bob = Customer.createIt("name", "Bob Sampson", "address", "123 Some St.", "city", "Pocatello", "state", "ID", "postal_code", "83201");
            bob.saveIt();
        }

        if (julie == null) {
            julie = Customer.builder()
                    .name("Julie Lark")
                    .address("456 Nowhere Ave.")
                    .city("Idaho Falls")
                    .state("ID")
                    .postalCode("83401")
                    .create();
        }

        Product prod = Product.findById(1);
        if (prod == null) {
            prod = Product.builder()
                    .description("Simple Test Product")
                    .finish("Nice")
                    .price(100.00)
                    .create();


        }

        Order order = Order.findById(1);
        if (order == null) {
            order = new Order();
            bob.add(order);
            order.addOrderLine(prod, 100);
        }

        new DB("default").close();

        new DB("default").open("com.mysql.cj.jdbc.Driver", "jdbc:mysql://localhost/test_db?serverTimezone=America/Denver", "idg", "caffeine");

        System.out.println("Customers: ");
        System.out.println("---------");
        Customer.findAll().forEach(System.out::println);

        System.out.println("Products:");
        System.out.println("--------");
        Product.findAll().forEach(System.out::println);

        System.out.println("Orders:");
        System.out.println("------");
        Order.findAll().forEach(System.out::println);

        new DB("default").close();
    }
}
