/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs.cs2263.examples.javadoc;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
